class AddKeys < ActiveRecord::Migration[5.2]
  def change
    add_foreign_key "allergens", "apps", name: "allergens_app_id_fk"
    add_foreign_key "allergens_recipes", "allergens", name: "allergens_recipes_allergen_id_fk"
    add_foreign_key "allergens_recipes", "recipes", name: "allergens_recipes_recipe_id_fk"
    add_foreign_key "apps", "plans", name: "apps_plan_id_fk"
    add_foreign_key "chefs", "users", name: "chefs_user_id_fk"
    add_foreign_key "comments", "chefs", name: "comments_chef_id_fk"
    add_foreign_key "comments", "recipes", name: "comments_recipe_id_fk"
    add_foreign_key "ingredients", "apps", name: "ingredients_app_id_fk"
    add_foreign_key "likes", "apps", name: "likes_app_id_fk"
    add_foreign_key "likes", "recipes", name: "likes_recipe_id_fk"
    add_foreign_key "mail_attachments", "email_contents", name: "mail_attachments_email_content_id_fk"
    add_foreign_key "messages", "chefs", name: "messages_chef_id_fk"
    add_foreign_key "pages", "apps", name: "pages_app_id_fk"
    add_foreign_key "plans", "plan_categories", name: "plans_plan_category_id_fk"
    add_foreign_key "questions", "recipes", name: "questions_recipe_id_fk"
    add_foreign_key "questions", "users", name: "questions_user_id_fk"
    add_foreign_key "recipe_images", "recipes", name: "recipe_images_recipe_id_fk"
    add_foreign_key "recipe_ingredients", "ingredients", name: "recipe_ingredients_ingredient_id_fk"
    add_foreign_key "recipe_ingredients", "recipes", name: "recipe_ingredients_recipe_id_fk"
    add_foreign_key "recipes", "chefs", name: "recipes_chef_id_fk"
    add_foreign_key "recipes_styles", "recipes", name: "recipes_styles_recipe_id_fk"
    add_foreign_key "recipes_styles", "styles", name: "recipes_styles_style_id_fk"
    add_foreign_key "reservations", "apps", name: "reservations_app_id_fk"
    add_foreign_key "reservations", "recipes", name: "reservations_recipe_id_fk"
    add_foreign_key "styles", "apps", name: "styles_app_id_fk"
    add_foreign_key "taggings", "tags", name: "taggings_tag_id_fk"
    add_foreign_key "users", "apps", name: "users_app_id_fk"
  end
end
